# Shared base config

# Site settings
title: Ônibus Hacker
description: >
  Ônibus Hacker é uma organização que promove trocas de conhecimentos.
  Esta organização é também um veículo, um laboratório e um espaço lúdico.
  A forma com que ela promove estas trocas é por meio de viagens e oficinas,
  organizadas coletivamente pelas pessoas (na maioria voluntárias) que a servem,
  de maneira aberta e transparente.
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

